module.exports = {
	aid: '/imgs/illustrations/aid.svg',
	environment: '/imgs/illustrations/ozone-layer.svg',
	city: '/imgs/illustrations/weapons.svg',
	democracy: '/imgs/illustrations/election.svg',
	energy: '/imgs/illustrations/atomic-energy.svg',
	food: '/imgs/illustrations/food.svg',
	health: '/imgs/illustrations/aid.svg',
	smallpox: '/imgs/illustrations/small-pox.svg',
	crimes: '/imgs/illustrations/war-crimes.svg',
	money: '/imgs/illustrations/un-charter.svg',
	refugees: '/imgs/illustrations/refugees.svg',
	rights: '/imgs/illustrations/human-rights.svg',
	terrorism: '/imgs/illustrations/weapons.svg',
	un: '/imgs/illustrations/un-charter.svg',
	weapons: '/imgs/illustrations/weapons.svg',
	war: '/imgs/illustrations/soldier.svg',
	peace: '/imgs/illustrations/peace.svg',
	nuclear: '/imgs/illustrations/nuclear-bomb.svg',
};
